development:
  host: "snowfinch.rails.fi:3000"
  mailer_sender: "support@snowfinch.net"
  mongo_database: "snowfinch"

test:
  host: "snowfinch.rails.fi:3000"
  mailer_sender: "support@snowfinch.net"
  mongo_database: "snowfinch_test"

production:
  host: "nest.snowfinch.net"
  mailer_sender: "support@snowfinch.net"
  mongo_database: "snowfinch"
