development:
  host: "localhost:3000"
  collector_uri: "http://localhost:3000/collector"
  mount_collector: true
  mailer_sender: "snowfinch@example.com"
  mongo_database: "snowfinch"

test:
  host: "localhost:3000"
  collector_uri: "http://localhost:3000/collector"
  mount_collector: true
  mailer_sender: "snowfinch@example.com"
  mongo_database: "snowfinch"

production:
  host: "example.com"
  collector_uri: "http://example.com/collector"
  mount_collector: true
  mailer_sender: "snowfinch@example.com"
  mongo_database: "snowfinch"
